[book]
language = "en"
multilingual = false
src = "src"
title = "PH Editor Reference Manual"
description = "The Reference Manual for all things related to the Project Heartbeat Editor."
authors = ["Lino Bigatti"]

[output.html]
git-repository-url = "https://github.com/LinoBigatti/ph-editor-reference/"
edit-url-template = "https://github.com/LinoBigatti/ph-editor-reference/edit/master/{path}"
